Veiculos: programa.cpp File Reference
programa.cpp File Reference
Enunciado:
#include <iostream>
#include <iomanip>
Classes
struct veiculo
Estrutura que descreve o veículo de acordo com o enunciado.
Macros
#define TAM_ESTOQUE 30
Functions
void cadastrar (struct veiculo ll[], int &pos)
Solicita ao usuário as informações do veículo.
void listar (struct veiculo ll[], int qtd_cadastrada)
Lista na saída padrão todos os veículos cadastrados em ll.
int main ()
Função principal do programa.
Detailed Description
Enunciado:
Implemente um programa de cadastro de veículos de uma loja (máximo 30). Use uma estrutura contendo: marca, modelo, ano e valor. Implemente uma função de cadastro e uma função que imprime na tela um relatório contendo o inventário do estoque.
Definition in file programa.cpp.
Macro Definition Documentation
#define TAM_ESTOQUE 30
Definition at line 20 of file programa.cpp.
Function Documentation
void cadastrar (struct veiculo ll[], int & pos)
Solicita ao usuário as informações do veículo.
Armazena no vetor ll os dados do veículo na posição pos.
Parameters
ll vetor que contêm os veículos.
pos posição para cadastrar o veículo.
Definition at line 85 of file programa.cpp.
References veiculo::ano, veiculo::marca, veiculo::modelo, and veiculo::valor.
Referenced by main().
void listar (struct veiculo ll[], int qtd_cadastrada)
Lista na saída padrão todos os veículos cadastrados em ll.
Parameters
ll vetor que contêm os veículos.
qtd_cadastrada quantidade de carros no vetor.
Definition at line 103 of file programa.cpp.
References veiculo::ano, veiculo::marca, veiculo::modelo, and veiculo::valor.
Referenced by main().
int main ()
Função principal do programa.
Returns
Status de fim do programa.
Definition at line 59 of file programa.cpp.
References cadastrar(), and listar().