Biblioteca: /home/gian/Dev/codigos-cpp/fundamentos/biblioteca/src/funcoes.h File Reference
funcoes.h File Reference
Estrutura e funções disponíveis.
#include "constantes.h"
#include <iostream>
Classes
struct livro
Definição de estrutura de um livro.
Typedefs
typedef struct livro ELivro
Tipo definido a partir da estrutura de livro.
Functions
int menu ()
Responsável pela apresentação do menu ao usuário.
void acao (ELivro livros[], int opcao_menu)
Função para executar a opção escolhida pelo usuário.
std::string solicitar_codigo ()
Função que questiona o usuário para fornecer um código.
int procurarLivro (std::string codigoParaProcurar, ELivro livros[])
Função que busca no vetor, o livro com o respectivo código fornecido.
void cadastrar (ELivro livros[])
Realiza o cadastro de um livro.
void consultar (ELivro livros[])
Consulta os dados do livro e apresenta ao usuário.
void devolver (ELivro livros[])
Realiza a devolução de um livro emprestado.
void emprestar (ELivro livros[])
Realiza o empréstimo de um livro emprestado.
Detailed Description
Estrutura e funções disponíveis.
Created on: Mar 30, 2015 Author: gian
Definition in file funcoes.h.
Typedef Documentation
typedef struct livro ELivro
Tipo definido a partir da estrutura de livro.
Definition at line 32 of file funcoes.h.
Function Documentation
void acao (ELivro livros[], int opcao_menu)
Função para executar a opção escolhida pelo usuário.
Parameters
livros Vetor com os livros disponíveis no programa.
opcao_menu Opção de menu que o usuário escolheu.
Definition at line 20 of file comportamentos-funcoes.cpp.
References cadastrar(), consultar(), devolver(), and emprestar().
Referenced by main().
void cadastrar (ELivro livros[])
Realiza o cadastro de um livro.
Solicita do usuário informações necessárias para cadastrar um livro no programa. O código do livro é gerado automaticamente e o estado inicial do livro é disponível para empréstimo.
Parameters
livros Vetor com os livros disponíveis no programa.
Definition at line 51 of file comportamentos-funcoes.cpp.
References livro::area, livro::autor, livro::codigo, livro::emprestado, procurarLivro(), SEM_CODIGO, and livro::titulo.
Referenced by acao().
void consultar (ELivro livros[])
Consulta os dados do livro e apresenta ao usuário.
Nessa função é solicitado um código de dois dígitos ao usuário. Com esse código uma busca é feita no vetor. Caso o livro seja encontrado, seus dados são apresentados. Caso contrário, uma mensagem é apresentada.
Parameters
livros Vetor com os livros disponíveis no programa.
Definition at line 102 of file comportamentos-funcoes.cpp.
References livro::area, livro::autor, livro::codigo, livro::emprestado, procurarLivro(), solicitar_codigo(), and livro::titulo.
Referenced by acao().
void devolver (ELivro livros[])
Realiza a devolução de um livro emprestado.
Nessa função é solicitado um código de dois dígitos ao usuário. Com esse código uma busca é feita no vetor. Caso o livro seja encontrado, será realizado a devolução do livro (emprestado = false). Caso contrário, uma mensagem é apresentada.
Parameters
livros Vetor com os livros disponíveis no programa.
Definition at line 127 of file comportamentos-funcoes.cpp.
References livro::emprestado, procurarLivro(), and solicitar_codigo().
Referenced by acao().
void emprestar (ELivro livros[])
Realiza o empréstimo de um livro emprestado.
Nessa função é solicitado um código de dois dígitos ao usuário. Com esse código uma busca é feita no vetor. Caso o livro seja encontrado, será realizado o empréstimo (emprestado = true). Caso contrário, uma mensagem é apresentada.
Parameters
livros Vetor com os livros disponíveis no programa.
Definition at line 153 of file comportamentos-funcoes.cpp.
References livro::emprestado, procurarLivro(), and solicitar_codigo().
Referenced by acao().
int menu ()
Responsável pela apresentação do menu ao usuário.
Essa função apresenta ao usuário um menu com as seguintes opções:
Cadastrar um livro?
Consultar um titulo?
Empréstimo de livro?
Devolução de livro?
Sair
Após solicita ao usuário a opção desejada.
Returns
Opção escolhida pelo usuário.
Definition at line 10 of file comportamentos-funcoes.cpp.
Referenced by main().
int procurarLivro (std::string codigoParaProcurar, ELivro livros[])
Função que busca no vetor, o livro com o respectivo código fornecido.
Parameters
codigoParaProcurar Código de identificação de um livro
livros Vetor com os livros disponíveis no programa.
Returns
Posição onde encontra-se o livro com o respectivo código. Retorna -1 se não encontrar o livro com o código.
Definition at line 88 of file comportamentos-funcoes.cpp.
References TOTAL_LIVROS.
Referenced by cadastrar(), consultar(), devolver(), and emprestar().
std::string solicitar_codigo ()
Função que questiona o usuário para fornecer um código.
Esse código será usado para buscar o livro relacionado com ele.
Returns
Código de um livro fornecido pelo usuário.
Definition at line 43 of file comportamentos-funcoes.cpp.
Referenced by consultar(), devolver(), and emprestar().